### ISSUE TITLE
It doesn't work at all

### ISSUE THREAD

**Issue by oe** [Apptorium/TeaCode-Sublime-Helper#1]
After installing this plugin, I tried to expand code in sublime text, TeaCode keeps pushing notifications of `Are you using a text editor?`

![image](https://user-images.githubusercontent.com/1655294/47635947-ab91cc80-db91-11e8-81d3-de59df345eb7.png)

BTW, If I have thousands code snippets, how can I remember so many expander patterns, it's unusable! 

Some suggestions:

## The `Quick browser...` searching is too slow and does support fuzzy search, the snippets search should be like:
1. can search `title` `pattern` `description` `language`  and even `code snippet content`.
2. should sort by priority above
3. should support fuzzy search
4. `description` and `language` should be in the result list

## How to expand the code
I think it better to expand after press <kbd>enter</kbd> when locate the snippet in `Quick browser...`.

Here are the steps to use it:
1. launch `Quick browser...`
2. fuzzy search my code snippets
3. locate the snippets and press <kbd>enter</kbd>
4. if the snippet has no var to fill, then skip this step. Or `Quick browser...` should auto navigate a `editor UI`(this UI belongs to TeaCode itself), user fills up the vars, then press a shortcut(like <kbd>cmd</kbd> + <kbd>enter</kdb>)
5. TeaCode should bring the last active app to front, then paste the code(just do <kbd>cmd</kbd> + <kbd>v</kbd>)
6. all done!

So snippet's pattern is meaningless, the editors' plugins are not necessary.

**Comment by mkk** [comment]
You should use ctrl+cmd+e. It's the shortcut for plugins.

Please send all the suggestions via https://www.apptorium.com/contacthttps://www.apptorium.com/contact 
**GitHub is made for plugins only**

You're also welcome to join our slack channel https://www.apptorium.com/teacode#slack

**Comment by oe** [comment]
My bad, it works.

But still too hard  to use
